defaults:
  - model/pi0_5_rlinf@actor.model
  - hybrid_engines/fsdp@actor.fsdp_config
  - override hydra/job_logging: stdout
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 1
  component_placement:
    actor,env,rollout: all

runner:
  task_type: sft
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "realagainst_peg_slot_dagger_round1_pi05_sft"
    logger_backends: ["tensorboard"]
  max_epochs: -1
  max_steps: 3000
  val_check_interval: -1
  save_interval: 1000

data:
  train_data_paths: "/mnt/public/chenyinuo/RealAgainst_new/RLinf/data/realagainst_peg_slot_dagger_round1"
  num_workers: 8

algorithm:
  adv_type: gae

actor:
  group_name: "ActorGroup"
  training_backend: "fsdp"
  micro_batch_size: 16
  eval_batch_size: 1
  global_batch_size: 32
  seed: 0

  model:
    precision: fp32
    model_path: "/mnt/public/chenyinuo/RealAgainst_new/RLinf/logs/archive/realagainst_peg_slot/2026-08-14_pi05_sft_step_10000"
    model_type: "openpi_rlinf"
    num_action_chunks: 10
    action_dim: 9
    add_value_head: false
    num_steps: 5
    openpi:
      task: sft
      config_name: "pi05_realagainst_peg_slot"
      num_images_in_input: 2
      action_horizon: 10
      action_chunk: ${actor.model.num_action_chunks}
      action_env_dim: ${actor.model.action_dim}
      num_steps: ${actor.model.num_steps}
      model_action_dim: 32
      paligemma_variant: "gemma_2b"
      action_expert_variant: "gemma_300m"
      max_token_len: 200
      discrete_state_input: true
      use_rlt: false

    openpi_data:
      repo_id: "data/realagainst_peg_slot_dagger_round1"
      default_prompt: "insert the grasped peg downward into the movable slot"
      norm_stats_path: "/mnt/public/chenyinuo/RealAgainst_new/RLinf/assets/pi05_realagainst_peg_slot/data/realagainst_peg_slot_dagger_round1/norm_stats.json"

  optim:
    lr: 1.0e-5
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-8
    weight_decay: 1.0e-10
    clip_grad: 1.0
    total_training_steps: 3000
    lr_warmup_steps: 300
    lr_scheduler: "openpi_cosine"
    num_cycles: 0.5
    min_lr: 1.0e-6

  fsdp_config:
    strategy: "fsdp"
    sharding_strategy: "full_shard"
    use_orig_params: true
    gradient_checkpointing: true
    gradient_checkpointing_use_reentrant: false
    mixed_precision:
      param_dtype: bf16
      reduce_dtype: fp32
      buffer_dtype: fp32

reward:
  use_reward_model: false

critic:
  use_critic_model: false
